
-- address_component
INSERT INTO type (id, category, name, description) VALUES ('101001', 'address_component', 'accounting', '');
INSERT INTO type (id, category, name, description) VALUES ('101002', 'address_component', 'airport', '');
INSERT INTO type (id, category, name, description) VALUES ('101003', 'address_component', 'amusement_park', '');
INSERT INTO type (id, category, name, description) VALUES ('101004', 'address_component', 'aquarium', '');
INSERT INTO type (id, category, name, description) VALUES ('101005', 'address_component', 'art_gallery', '');
INSERT INTO type (id, category, name, description) VALUES ('101006', 'address_component', 'atm', '');
INSERT INTO type (id, category, name, description) VALUES ('101007', 'address_component', 'bakery', '');
INSERT INTO type (id, category, name, description) VALUES ('101008', 'address_component', 'bank', '');
INSERT INTO type (id, category, name, description) VALUES ('101009', 'address_component', 'bar', '');
INSERT INTO type (id, category, name, description) VALUES ('101010', 'address_component', 'beauty_salon', '');
INSERT INTO type (id, category, name, description) VALUES ('101011', 'address_component', 'bicycle_store', '');
INSERT INTO type (id, category, name, description) VALUES ('101012', 'address_component', 'book_store', '');
INSERT INTO type (id, category, name, description) VALUES ('101013', 'address_component', 'bowling_alley', '');
INSERT INTO type (id, category, name, description) VALUES ('101014', 'address_component', 'bus_station', '');
INSERT INTO type (id, category, name, description) VALUES ('101015', 'address_component', 'cafe', '');
INSERT INTO type (id, category, name, description) VALUES ('101016', 'address_component', 'campground', '');
INSERT INTO type (id, category, name, description) VALUES ('101017', 'address_component', 'car_dealer', '');
INSERT INTO type (id, category, name, description) VALUES ('101018', 'address_component', 'car_rental', '');
INSERT INTO type (id, category, name, description) VALUES ('101019', 'address_component', 'car_repair', '');
INSERT INTO type (id, category, name, description) VALUES ('101020', 'address_component', 'car_wash', '');
INSERT INTO type (id, category, name, description) VALUES ('101021', 'address_component', 'casino', '');
INSERT INTO type (id, category, name, description) VALUES ('101022', 'address_component', 'cemetery', '');
INSERT INTO type (id, category, name, description) VALUES ('101023', 'address_component', 'church', '');
INSERT INTO type (id, category, name, description) VALUES ('101024', 'address_component', 'city_hall', '');
INSERT INTO type (id, category, name, description) VALUES ('101025', 'address_component', 'clothing_store', '');
INSERT INTO type (id, category, name, description) VALUES ('101026', 'address_component', 'convenience_store', '');
INSERT INTO type (id, category, name, description) VALUES ('101027', 'address_component', 'courthouse', '');
INSERT INTO type (id, category, name, description) VALUES ('101028', 'address_component', 'dentist', '');
INSERT INTO type (id, category, name, description) VALUES ('101029', 'address_component', 'department_store', '');
INSERT INTO type (id, category, name, description) VALUES ('101030', 'address_component', 'doctor', '');
INSERT INTO type (id, category, name, description) VALUES ('101031', 'address_component', 'drugstore', '');
INSERT INTO type (id, category, name, description) VALUES ('101032', 'address_component', 'electrician', '');
INSERT INTO type (id, category, name, description) VALUES ('101033', 'address_component', 'electronics_store', '');
INSERT INTO type (id, category, name, description) VALUES ('101034', 'address_component', 'embassy', '');
INSERT INTO type (id, category, name, description) VALUES ('101035', 'address_component', 'fire_station', '');
INSERT INTO type (id, category, name, description) VALUES ('101036', 'address_component', 'florist', '');
INSERT INTO type (id, category, name, description) VALUES ('101037', 'address_component', 'funeral_home', '');
INSERT INTO type (id, category, name, description) VALUES ('101038', 'address_component', 'furniture_store', '');
INSERT INTO type (id, category, name, description) VALUES ('101039', 'address_component', 'gas_station', '');
INSERT INTO type (id, category, name, description) VALUES ('101040', 'address_component', 'gym', '');
INSERT INTO type (id, category, name, description) VALUES ('101041', 'address_component', 'hair_care', '');
INSERT INTO type (id, category, name, description) VALUES ('101042', 'address_component', 'hardware_store', '');
INSERT INTO type (id, category, name, description) VALUES ('101043', 'address_component', 'hindu_temple', '');
INSERT INTO type (id, category, name, description) VALUES ('101044', 'address_component', 'home_goods_store', '');
INSERT INTO type (id, category, name, description) VALUES ('101045', 'address_component', 'hospital', '');
INSERT INTO type (id, category, name, description) VALUES ('101046', 'address_component', 'insurance_agency', '');
INSERT INTO type (id, category, name, description) VALUES ('101047', 'address_component', 'jewelry_store', '');
INSERT INTO type (id, category, name, description) VALUES ('101048', 'address_component', 'laundry', '');
INSERT INTO type (id, category, name, description) VALUES ('101049', 'address_component', 'lawyer', '');
INSERT INTO type (id, category, name, description) VALUES ('101050', 'address_component', 'library', '');
INSERT INTO type (id, category, name, description) VALUES ('101051', 'address_component', 'light_rail_station', '');
INSERT INTO type (id, category, name, description) VALUES ('101052', 'address_component', 'liquor_store', '');
INSERT INTO type (id, category, name, description) VALUES ('101053', 'address_component', 'local_government_office', '');
INSERT INTO type (id, category, name, description) VALUES ('101054', 'address_component', 'locksmith', '');
INSERT INTO type (id, category, name, description) VALUES ('101055', 'address_component', 'lodging', '');
INSERT INTO type (id, category, name, description) VALUES ('101056', 'address_component', 'meal_delivery', '');
INSERT INTO type (id, category, name, description) VALUES ('101057', 'address_component', 'meal_takeaway', '');
INSERT INTO type (id, category, name, description) VALUES ('101058', 'address_component', 'mosque', '');
INSERT INTO type (id, category, name, description) VALUES ('101059', 'address_component', 'movie_rental', '');
INSERT INTO type (id, category, name, description) VALUES ('101060', 'address_component', 'movie_theater', '');
INSERT INTO type (id, category, name, description) VALUES ('101061', 'address_component', 'moving_company', '');
INSERT INTO type (id, category, name, description) VALUES ('101062', 'address_component', 'museum', '');
INSERT INTO type (id, category, name, description) VALUES ('101063', 'address_component', 'night_club', '');
INSERT INTO type (id, category, name, description) VALUES ('101064', 'address_component', 'painter', '');
INSERT INTO type (id, category, name, description) VALUES ('101065', 'address_component', 'park', '');
INSERT INTO type (id, category, name, description) VALUES ('101066', 'address_component', 'parking', '');
INSERT INTO type (id, category, name, description) VALUES ('101067', 'address_component', 'pet_store', '');
INSERT INTO type (id, category, name, description) VALUES ('101068', 'address_component', 'pharmacy', '');
INSERT INTO type (id, category, name, description) VALUES ('101069', 'address_component', 'physiotherapist', '');
INSERT INTO type (id, category, name, description) VALUES ('101070', 'address_component', 'plumber', '');
INSERT INTO type (id, category, name, description) VALUES ('101071', 'address_component', 'police', '');
INSERT INTO type (id, category, name, description) VALUES ('101072', 'address_component', 'post_office', '');
INSERT INTO type (id, category, name, description) VALUES ('101073', 'address_component', 'primary_school', '');
INSERT INTO type (id, category, name, description) VALUES ('101074', 'address_component', 'real_estate_agency', '');
INSERT INTO type (id, category, name, description) VALUES ('101075', 'address_component', 'restaurant', '');
INSERT INTO type (id, category, name, description) VALUES ('101076', 'address_component', 'roofing_contractor', '');
INSERT INTO type (id, category, name, description) VALUES ('101077', 'address_component', 'rv_park', '');
INSERT INTO type (id, category, name, description) VALUES ('101078', 'address_component', 'school', '');
INSERT INTO type (id, category, name, description) VALUES ('101079', 'address_component', 'secondary_school', '');
INSERT INTO type (id, category, name, description) VALUES ('101080', 'address_component', 'shoe_store', '');
INSERT INTO type (id, category, name, description) VALUES ('101081', 'address_component', 'shopping_mall', '');
INSERT INTO type (id, category, name, description) VALUES ('101082', 'address_component', 'spa', '');
INSERT INTO type (id, category, name, description) VALUES ('101083', 'address_component', 'stadium', '');
INSERT INTO type (id, category, name, description) VALUES ('101084', 'address_component', 'storage', '');
INSERT INTO type (id, category, name, description) VALUES ('101085', 'address_component', 'store', '');
INSERT INTO type (id, category, name, description) VALUES ('101086', 'address_component', 'subway_station', '');
INSERT INTO type (id, category, name, description) VALUES ('101087', 'address_component', 'supermarket', '');
INSERT INTO type (id, category, name, description) VALUES ('101088', 'address_component', 'synagogue', '');
INSERT INTO type (id, category, name, description) VALUES ('101089', 'address_component', 'taxi_stand', '');
INSERT INTO type (id, category, name, description) VALUES ('101090', 'address_component', 'tourist_attraction', '');
INSERT INTO type (id, category, name, description) VALUES ('101091', 'address_component', 'train_station', '');
INSERT INTO type (id, category, name, description) VALUES ('101092', 'address_component', 'transit_station', '');
INSERT INTO type (id, category, name, description) VALUES ('101093', 'address_component', 'travel_agency', '');
INSERT INTO type (id, category, name, description) VALUES ('101094', 'address_component', 'university', '');
INSERT INTO type (id, category, name, description) VALUES ('101095', 'address_component', 'veterinary_care', '');
INSERT INTO type (id, category, name, description) VALUES ('101096', 'address_component', 'zoo', '');



-- business_status
INSERT INTO type (id, category, name, description) VALUES ('102001', 'business_status', 'OPERATIONAL', '');
INSERT INTO type (id, category, name, description) VALUES ('102002', 'business_status', 'CLOSED_TEMPORARILY', '');
INSERT INTO type (id, category, name, description) VALUES ('102003', 'business_status', 'CLOSED_PERMANENTLY', '');

-- opneing_hour
INSERT INTO type (id, category, name, description) VALUES ('103001', 'opneing_hour', 'DRIVE_THROUGH', '');
INSERT INTO type (id, category, name, description) VALUES ('103002', 'opneing_hour', 'HAPPY_HOUR', '');
INSERT INTO type (id, category, name, description) VALUES ('103003', 'opneing_hour', 'DELIVERY', '');
INSERT INTO type (id, category, name, description) VALUES ('103004', 'opneing_hour', 'TAKEOUT', '');
INSERT INTO type (id, category, name, description) VALUES ('103005', 'opneing_hour', 'KITCHEN', '');
INSERT INTO type (id, category, name, description) VALUES ('103006', 'opneing_hour', 'BREAKFAST', '');
INSERT INTO type (id, category, name, description) VALUES ('103007', 'opneing_hour', 'LUNCH', '');
INSERT INTO type (id, category, name, description) VALUES ('103008', 'opneing_hour', 'DINNER', '');
INSERT INTO type (id, category, name, description) VALUES ('103009', 'opneing_hour', 'BRUNCH', '');
INSERT INTO type (id, category, name, description) VALUES ('103010', 'opneing_hour', 'PICKUP', '');
INSERT INTO type (id, category, name, description) VALUES ('103011', 'opneing_hour', 'SENIOR_HOURS', '');

-- place
INSERT INTO type (id, category, name, description) VALUES ('104001', 'place', 'administrative_area_level_1', '');
INSERT INTO type (id, category, name, description) VALUES ('104002', 'place', 'administrative_area_level_2', '');
INSERT INTO type (id, category, name, description) VALUES ('104003', 'place', 'administrative_area_level_3', '');
INSERT INTO type (id, category, name, description) VALUES ('104004', 'place', 'administrative_area_level_4', '');
INSERT INTO type (id, category, name, description) VALUES ('104005', 'place', 'administrative_area_level_5', '');
INSERT INTO type (id, category, name, description) VALUES ('104006', 'place', 'administrative_area_level_6', '');
INSERT INTO type (id, category, name, description) VALUES ('104007', 'place', 'administrative_area_level_7', '');
INSERT INTO type (id, category, name, description) VALUES ('104008', 'place', 'archipelago', '');
INSERT INTO type (id, category, name, description) VALUES ('104009', 'place', 'colloquial_area', '');
INSERT INTO type (id, category, name, description) VALUES ('104010', 'place', 'continent', '');
INSERT INTO type (id, category, name, description) VALUES ('104011', 'place', 'country', '');
INSERT INTO type (id, category, name, description) VALUES ('104012', 'place', 'establishment', '');
INSERT INTO type (id, category, name, description) VALUES ('104013', 'place', 'finance', '');
INSERT INTO type (id, category, name, description) VALUES ('104014', 'place', 'floor', '');
INSERT INTO type (id, category, name, description) VALUES ('104015', 'place', 'food', '');
INSERT INTO type (id, category, name, description) VALUES ('104016', 'place', 'general_contractor', '');
INSERT INTO type (id, category, name, description) VALUES ('104017', 'place', 'geocode', '');
INSERT INTO type (id, category, name, description) VALUES ('104018', 'place', 'health', '');
INSERT INTO type (id, category, name, description) VALUES ('104019', 'place', 'intersection', '');
INSERT INTO type (id, category, name, description) VALUES ('104020', 'place', 'landmark', '');
INSERT INTO type (id, category, name, description) VALUES ('104021', 'place', 'locality', '');
INSERT INTO type (id, category, name, description) VALUES ('104022', 'place', 'natural_feature', '');
INSERT INTO type (id, category, name, description) VALUES ('104023', 'place', 'neighborhood', '');
INSERT INTO type (id, category, name, description) VALUES ('104024', 'place', 'place_of_worship', '');
INSERT INTO type (id, category, name, description) VALUES ('104025', 'place', 'plus_code', '');
INSERT INTO type (id, category, name, description) VALUES ('104026', 'place', 'point_of_interest', '');
INSERT INTO type (id, category, name, description) VALUES ('104027', 'place', 'political', '');
INSERT INTO type (id, category, name, description) VALUES ('104028', 'place', 'post_box', '');
INSERT INTO type (id, category, name, description) VALUES ('104029', 'place', 'postal_code', '');
INSERT INTO type (id, category, name, description) VALUES ('104030', 'place', 'postal_code_prefix', '');
INSERT INTO type (id, category, name, description) VALUES ('104031', 'place', 'postal_code_suffix', '');
INSERT INTO type (id, category, name, description) VALUES ('104032', 'place', 'postal_town', '');
INSERT INTO type (id, category, name, description) VALUES ('104033', 'place', 'premise', '');
INSERT INTO type (id, category, name, description) VALUES ('104034', 'place', 'room', '');
INSERT INTO type (id, category, name, description) VALUES ('104035', 'place', 'route', '');
INSERT INTO type (id, category, name, description) VALUES ('104036', 'place', 'street_address', '');
INSERT INTO type (id, category, name, description) VALUES ('104037', 'place', 'street_number', '');
INSERT INTO type (id, category, name, description) VALUES ('104038', 'place', 'sublocality', '');
INSERT INTO type (id, category, name, description) VALUES ('104039', 'place', 'sublocality_level_1', '');
INSERT INTO type (id, category, name, description) VALUES ('104040', 'place', 'sublocality_level_2', '');
INSERT INTO type (id, category, name, description) VALUES ('104041', 'place', 'sublocality_level_3', '');
INSERT INTO type (id, category, name, description) VALUES ('104042', 'place', 'sublocality_level_4', '');
INSERT INTO type (id, category, name, description) VALUES ('104043', 'place', 'sublocality_level_5', '');
INSERT INTO type (id, category, name, description) VALUES ('104044', 'place', 'subpremise', '');
INSERT INTO type (id, category, name, description) VALUES ('104045', 'place', 'town_square', '');


-- place_feature
INSERT INTO type (id, category, name, description) VALUES ('105001', 'place_feature', 'curbside_pickup', 'Specifies if the business supports curbside pickup');
INSERT INTO type (id, category, name, description) VALUES ('105002', 'place_feature', 'delivery', 'Specifies if the business supports delivery');
INSERT INTO type (id, category, name, description) VALUES ('105003', 'place_feature', 'dine_in', 'Specifies if the business supports indoor or outdoor seating');
INSERT INTO type (id, category, name, description) VALUES ('105004', 'place_feature', 'reservable', 'Specifies if the place supports reservations');
INSERT INTO type (id, category, name, description) VALUES ('105005', 'place_feature', 'serves_beer', 'Specifies if the place serves beer');
INSERT INTO type (id, category, name, description) VALUES ('105006', 'place_feature', 'serves_breakfast', 'Specifies if the place serves breakfast');
INSERT INTO type (id, category, name, description) VALUES ('105007', 'place_feature', 'serves_brunch', 'Specifies if the place serves brunch');
INSERT INTO type (id, category, name, description) VALUES ('105008', 'place_feature', 'serves_dinner', 'Specifies if the place serves dinner');
INSERT INTO type (id, category, name, description) VALUES ('105009', 'place_feature', 'serves_lunch', 'Specifies if the place serves lunch');
INSERT INTO type (id, category, name, description) VALUES ('105010', 'place_feature', 'serves_vegetarian_food', 'Specifies if the place serves vegetarian food');
INSERT INTO type (id, category, name, description) VALUES ('105011', 'place_feature', 'serves_wine', 'Specifies if the place serves wine');
INSERT INTO type (id, category, name, description) VALUES ('105012', 'place_feature', 'takeout', 'Specifies if the business supports takeout');
INSERT INTO type (id, category, name, description) VALUES ('105013', 'place_feature', 'wheelchair_accessible_entrance', 'Specifies if the place has a wheelchair-accessible entrance');

